name: Build and Push openvpn+frp Docker Image

# 触发条件：推送到 main 分支、PR 合并到 main 或手动触发
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 拉取源码
      - name: Checkout code
        uses: actions/checkout@v3

      # 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 设置执行权限
      - name: Set execute permissions for entrypoint.sh
        run: chmod +x entrypoint.sh

      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/openvpn-frp:v0.1 .

      # 推送 v0.1 镜像
      - name: Push Docker image with v0.1 tag
        run: docker push ${{ secrets.DOCKER_USERNAME }}/openvpn-frp:v0.1

      # 推送 latest 镜像
      - name: Tag and push latest image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/openvpn-frp:v0.1 ${{ secrets.DOCKER_USERNAME }}/openvpn-frp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/openvpn-frp:latest
