name: Build and Push Docker Image

# 触发条件：推送到 main 分支或手动触发
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Docker 登录凭证
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. 设置 Docker Buildx（多平台支持）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. 设置执行权限
      - name: Set execute permissions for entrypoint.sh
        run: chmod +x entrypoint.sh

      # 5. 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/openvpn-frp:latest --push .

      # 6. 推送 Docker 镜像到 Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/openvpn-frp:latest

      # 7. 推送带版本号的标签（可选）
      - name: Tag and push versioned image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/openvpn-frp:latest ${{ secrets.DOCKER_USERNAME }}/openvpn-frp:v1.1
          docker push ${{ secrets.DOCKER_USERNAME }}/openvpn-frp:v1.1
