name: Build and Push openvpn+frp Multi-Arch Docker Image

# 当 main 分支发生 push、PR 合并，或手动点击触发 workflow 时运行
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions 使用 Ubuntu 虚拟机执行任务

    steps:
      # 第一步：拉取项目源码
      - name: Checkout code
        uses: actions/checkout@v3

      # 第二步：设置支持多平台构建的 Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 第三步：登录 Docker Hub（账号密码从 secrets 中获取）
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # 你的 Docker Hub 用户名
          password: ${{ secrets.DOCKER_PASSWORD }}  # 你的 Docker Hub 密码

      # 第四步：为 entrypoint.sh 添加执行权限（如果有）
      - name: Set execute permissions for entrypoint.sh
        run: chmod +x entrypoint.sh

      # 第五步：构建并推送支持多架构（amd64 + arm64）的 Docker 镜像
      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # 使用当前目录作为构建上下文
          push: true  # 构建完成后自动推送镜像
          platforms: linux/amd64,linux/arm64  # 支持的平台架构，可加 linux/arm/v7
          tags: |  # 设置多个 tag
            ${{ secrets.DOCKER_USERNAME }}/openvpn-frp:v0.1
            ${{ secrets.DOCKER_USERNAME }}/openvpn-frp:latest
